workflow "Push to master" {
  on = "push"
  resolves = [
    "publish-hugo-site",
  ]
}

action "hugo branch" {
  uses = "actions/bin/filter@master"
  args = "branch hugo"
}

action "publish-hugo-site" {
  needs = "hugo branch"
  uses = "tcitry/publish-hugo-site@v1.0"
  env = {
    TARGET_REPO = "tcitry/tcitry.github.io"
    CNAME = "yindongliang.com"
  }
  secrets = ["TOKEN"]
  args = "<Pages branch>"
}
